### PR TITLE
Revert "[ImgBot] optimizes images"

### PR DESCRIPTION
**Pull request by punker76**
Reverts punker76/jekyll.jkarger.de#4

### CODE REVIEW

**Comment by dabutvin** [comment]
Sorry you had to revert the image optimizations from ImgBot.

If there is any information or feedback on the service I would love to hear about it so we can make the service better for everyone.
Was there a problem with the compression?

Thanks in advance

**Comment by punker76** [comment]
@dabutvin No :-D it was my fault. I'm using it on the wrong branch... I'll create a master branch with my jekyll original stuff and then use your awesome bot again on the static generated gh-pages branch.

thx for this nice bot 👍

**Comment by punker76** [comment]
@dabutvin How can I point the bot to a specific branch? Is this possible?

**Comment by dabutvin** [comment]
right now we are hardcoded to the 'master' branch :(

Definitely something we need to address. I think a config file in the root of the repro that we could parse as we do the image work would work for this case.

Feel free to add any of your own thoughts to these existing issues or open a new issue if you feel that's appropriate.

https://github.com/dabutvin/ImgBot/issues/2
https://github.com/dabutvin/ImgBot/issues/16


Thanks for the support!

**Comment by punker76** [comment]
@dabutvin do you mean the 'master' which is the default selected on GitHub or the branch with the name 'master'?

**Comment by dabutvin** [comment]
I have the branch name 'master' hardcoded in the app, but what I have found is that if there is no branch of that name, GitHub will actually use the default branch of whatever name.

Either way, making it configurable is the goal

**Comment by punker76** [comment]
@dabutvin nice!

**Pull request merged**
